//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_newhud_H
#define METASPRITE_newhud_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define newhud_TILE_ORIGIN 0
#define newhud_TILE_W 8
#define newhud_TILE_H 8
#define newhud_WIDTH 160
#define newhud_HEIGHT 8
#define newhud_TILE_COUNT 0
#define newhud_PALETTE_COUNT 8
#define newhud_COLORS_PER_PALETTE 4
#define newhud_TOTAL_COLORS 32
#define newhud_MAP_ATTRIBUTES newhud_map_attributes
#define newhud_MAP_ATTRIBUTES_WIDTH 20
#define newhud_MAP_ATTRIBUTES_HEIGHT 1
#define newhud_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define newhud_MAP_ATTRIBUTES_PACKED_HEIGHT 1
extern const unsigned char newhud_map[20];
extern const unsigned char newhud_map_attributes[20];

BANKREF_EXTERN(newhud)


#endif
